parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                charset:          '%env(resolve:DATABASE_CHARSET)%'
                dbname:           '%env(resolve:DATABASE_NAME)%'
                driver:           '%env(resolve:DATABASE_DRIVER)%'
                host:             '%env(resolve:DATABASE_HOST)%'
                password:         '%env(resolve:DATABASE_PASSWORD)%'
                port:             '%env(resolve:DATABASE_PORT)%'
                options:          '%pdo_options%'
                schema_filter:    '%env(resolve:DATABASE_FILTER)%'
                server_version:   '%env(resolve:DATABASE_VERSION)%'
                user:             '%env(resolve:DATABASE_USER)%'
                default_table_options:
                    charset:      '%env(resolve:DATABASE_CHARSET)%'
                    collate:      '%env(resolve:DATABASE_COLLATE)%'
                mapping_types:  
                    json: string
        types:
            json: App\Doctrine\Types\JsonType
            datetime: App\Doctrine\Types\DateTimeType
        #mapping_types:
        #    json: string
        #    uuid: char(36)
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'

        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                #metadata_cache_driver: apc
                #query_cache_driver: apc
                second_level_cache:
                    enabled: false
                    log_enabled: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        prefix: App\Entity
                        dir: "%kernel.project_dir%/src/Entity"
                    GedmoTree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        #alias: GedmoTree # (optional) it will default to the name set for the mapping
