on:
  [push, pull_request]

name: Check code style Workflow
# derived from https://github.com/shivammathur/setup-php/blob/master/examples/symfony-mysql.yml

jobs:
  codestyle:
    name: Check code style
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v1 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql
          #coverage: xdebug #optional
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: |
          php -r 'copy("https://getcomposer.org/composer-2.phar", "composer2");'
          php composer2 install --no-progress --prefer-dist --optimize-autoloader

      - name: Run Symplify Easy Coding Standard
        run: |
          php vendor/bin/ecs check --no-progress-bar src/

