on:
  [push, pull_request]

name: Symfony Security Checker

jobs:
  symfony_security_checker:
    name: Check composer.lock
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        id: cache-db
        with:
          path: ~/.symfony/cache
          key: db
      - name: Check
        uses: symfonycorp/security-checker-action@v1

